### PR TITLE
fix: change avatar column type to TEXT to support long URLs

### LINKED ISSUE #1498: avatar column in user table is too small
## Describe the bug

Currently the type is `character varying(1024)`. I have seen errors in the logs where this length is not sufficient. Maybe it should just be text or at least double the size in case you want to put a limit on it?

See this log:

```
Feb 05 09:44:56 chirpstack-support answer[2147189]: 2026-02-05 09:44:56.921        DEBUG        controller/connector_controller.go:134        connector received: {ExternalID:XXXXXX DisplayName:XXXX XXXXXX Username:XXXXX XXXXX Email:XXXXXXX Avatar:https://lh3.googleusercontent.com/[1000+ chars string] MetaInfo:{
Feb 05 09:44:56 chirpstack-support answer[2147189]:   "sub": "XXXX",
Feb 05 09:44:56 chirpstack-support answer[2147189]:   "name": "XXXXXX",
Feb 05 09:44:56 chirpstack-support answer[2147189]:   "given_name": "XXXXXX ",
Feb 05 09:44:56 chirpstack-support answer[2147189]:   "family_name": "XXXX",
Feb 05 09:44:56 chirpstack-support answer[2147189]:   "picture": "https://lh3.googleusercontent.com/a-/[1000+ chars string]",
Feb 05 09:44:56 chirpstack-support answer[2147189]:   "email": "XXXXX",
Feb 05 09:44:56 chirpstack-support answer[2147189]:   "email_verified": true,
Feb 05 09:44:56 chirpstack-support answer[2147189]:   "hd": "XXXXXXX"
Feb 05 09:44:56 chirpstack-support answer[2147189]: }}
Feb 05 09:44:57 chirpstack-support answer[2147189]: 2026-02-05 09:44:57.646        ERROR        controller/connector_controller.go:146        external login failed: code: 500, reason: base.database_error, message: , error: pq: value too long for type character varying(1024)
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/apache/answer/internal/repo/user/user_repo.go:66 github.com/apache/answer/internal/repo/user.(*userRepo).AddUser.func1
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/xorm.io/xorm/engine.go:1423 xorm.io/xorm.(*Engine).Transaction
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/apache/answer/internal/repo/user/user_repo.go:54 github.com/apache/answer/internal/repo/user.(*userRepo).AddUser
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/apache/answer/internal/service/user_external_login/user_external_login_service.go:209 github.com/apache/answer/internal/service/user_external_login.(*UserExternalLoginService).registerNewUser
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/apache/answer/internal/service/user_external_login/user_external_login_service.go:156 github.com/apache/answer/internal/service/user_external_login.(*UserExternalLoginService).ExternalLogin
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/apache/answer/internal/controller/connector_controller.go:144 github.com/apache/answer/internal/controller.(*ConnectorController).ConnectorRedirectDispatcher.(*ConnectorController).ConnectorRedirect.func2
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/apache/answer/internal/controller/connector_controller.go:97 github.com/apache/answer/internal/controller.(*ConnectorController).ConnectorRedirectDispatcher
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/gin-gonic/gin/context.go:185 github.com/gin-gonic/gin.(*Context).Next
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/anargu/gin-brotli/gin_brotli.go:71 github.com/apache/answer/internal/base/server.NewHTTPServer.Brotli.func3
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/gin-gonic/gin/context.go:185 github.com/gin-gonic/gin.(*Context).Next
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/gin-gonic/gin/gin.go:633 github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
Feb 05 09:44:57 chirpstack-support answer[2147189]: /apache-answer-2.0.0-bin-linux-amd64/answer_build3005906725/vendor/github.com/gin-gonic/gin/gin.go:589 github.com/gin-gonic/gin.(*Engine).ServeHTTP
Feb 05 09:44:57 chirpstack-support answer[2147189]: /nix/store/4wc5q32wgrhac7vb4da1zclhvw7r01wx-go-1.25.5/share/go/src/net/http/server.go:3340 net/http.serverHandler.ServeHTTP
Feb 05 09:44:57 chirpstack-support answer[2147189]: /nix/store/4wc5q32wgrhac7vb4da1zclhvw7r01wx-go-1.25.5/share/go/src/net/http/server.go:2109 net/http.(*conn).serve
Feb 05 09:44:57 chirpstack-support answer[2147189]: /nix/store/4wc5q32wgrhac7vb4da1zclhvw7r01wx-go-1.25.5/share/go/src/runtime/asm_amd64.s:1693 runtime.goexit
 ```

This happens rarely and I can not reproduce it myself, but seems that there are cases where the picture / avatar URL is longer than can be stored in the database column. Maybe a `text` type would be better?

The exact picture URL has a length of 1127 chars and it is a valid URL. I believe this URL is received through the Google login user claims, I assume in this case the user is simply unable to login with his / her Google account because of this.

## Platform

- Version: v2.0.0

### PR DESCRIPTION
**Pull request by maishivamhoo123**
### Type of change
- [x] Bug fix
#1498

### Description
This PR changes the `avatar` column type from `VARCHAR` to `TEXT` in the `user` table.

**Reason:**
Some Google profile image URLs exceed the previous character limit (1024/2048 chars), causing 500 errors during login or registration. Switching to `TEXT` ensures support for long URLs (up to 65kb).

### Changes
1. **Entity:** Updated `User` struct in `internal/entity/user_entity.go` to use `TEXT` for the avatar field.
2. **Migration:** Added `v1.8.2` migration (`internal/migrations/v32.go`) to alter the database column automatically.

### Verification
- Tested locally with MySQL.
- Verified that inserting a string longer than 2048 characters into the `avatar` column now succeeds without error.

### CODE REVIEW

**Comment by maishivamhoo123** [comment]
@LinkinStars @team can you please review this pr.
Thank you!

File: internal/migrations/migrations.go [hunk 1]
```diff
@@ -107,6 +107,7 @@ var migrations = []Migration{
 	NewMigration("v1.7.2", "expand avatar column length", expandAvatarColumnLength, false),
 	NewMigration("v1.8.0", "change admin menu", updateAdminMenuSettings, true),
 	NewMigration("v1.8.1", "ai feat", aiFeat, true),
+	NewMigration("v1.8.2", "change avatar type to text", updateAvatarType, false),
```
Comment (LinkinStars) [inline internal/migrations/migrations.go]: This version number should be v2.0.1

**Review by LinkinStars — CHANGES_REQUESTED** [review]

**Comment by LinkinStars** [comment]
@maishivamhoo123 After testing, we found an error. This is an error encountered during testing with MySQL. You may need to verify whether the migration works correctly for different database types.
`migrate failed:  sync user table failed: Error 1101 (42000): BLOB, TEXT, GEOMETRY or JSON column 'avatar' can't have a default value`

**Comment by maishivamhoo123** [comment]
> @maishivamhoo123 After testing, we found an error. This is an error encountered during testing with MySQL. You may need to verify whether the migration works correctly for different database types. `migrate failed: sync user table failed: Error 1101 (42000): BLOB, TEXT, GEOMETRY or JSON column 'avatar' can't have a default value`

@LinkinStars  sir i have migrated the version to  v2.0.1 and i removed the default tag from Avatar .
can you please review the new PR thank you sir.

**Review by LinkinStars — APPROVED** [review]

**Comment by maishivamhoo123** [comment]
@LinkinStars can you please for approve for workflows

**Comment by LinkinStars** [comment]
> @LinkinStars can you please for approve for workflows

Approved. This PR will be merged in future.
